"""Tradovate demo broker adapter.

Implements `BrokerAdapter` against the documented REST endpoints:

| purpose | call |
|---|---|
| authenticate | `POST /auth/accesstokenrequest` (see `auth.py`) |
| place an order | `POST /order/placeorder` |
| cancel an order | `POST /order/cancelorder` |
| account orders | `GET /order/deps?masterid=...` |
| account positions | `GET /position/deps?masterid=...` |
| accounts | `GET /account/list` |

**`isAutomated` is always true.** Exchange policy requires any order not physically
triggered by a human to be flagged as automated. Every order this system sends is
generated by code, so the flag is set unconditionally rather than being configurable —
there is no correct value of `false` for this application, and a configurable one is a
misreporting waiting to happen.

**This adapter reaches a demo host only.** `auth.rest_base_url` raises
`LiveTradingDisabled` for the live environment, so there is no path from here to a
real-money venue in v1.
"""

from __future__ import annotations

from datetime import datetime
from math import isfinite
from urllib.parse import quote

from ...core.clock import MARKET_TZ, Clock, SystemClock
from ...core.models import Fill, Order, new_id
from ...core.types import OrderStatus, OrderType, Side, TimeInForce
from ...instruments.registry import InstrumentSpec
from ..base import (
    BrokerAccount,
    BrokerCapabilities,
    BrokerConnectionError,
    BrokerEvent,
    BrokerOrderState,
    BrokerPosition,
    EventKind,
    NotConnected,
    OrderAck,
    OrderRejected,
)
from .auth import Authenticator, Credentials, Environment, load_credentials, rest_base_url
from .transport import RestClient, Transport

# Tradovate's vocabulary, mapped once.
_ACTION = {Side.BUY: "Buy", Side.SELL: "Sell"}
_ORDER_TYPE = {
    OrderType.MARKET: "Market",
    OrderType.LIMIT: "Limit",
    OrderType.STOP: "Stop",
    OrderType.STOP_LIMIT: "StopLimit",
}
_TIME_IN_FORCE = {
    TimeInForce.DAY: "Day",
    TimeInForce.GTC: "GTC",
    TimeInForce.IOC: "IOC",
}
_STATUS = {
    "Working": OrderStatus.ACCEPTED,
    "Completed": OrderStatus.FILLED,
    "Filled": OrderStatus.FILLED,
    "Canceled": OrderStatus.CANCELLED,
    "Cancelled": OrderStatus.CANCELLED,
    "Rejected": OrderStatus.REJECTED,
    "Expired": OrderStatus.EXPIRED,
    "PendingNew": OrderStatus.SUBMITTED,
    "PendingCancel": OrderStatus.CANCEL_REQUESTED,
    "Suspended": OrderStatus.ACCEPTED,
}


class TradovateBroker:
    """Demo-environment Tradovate adapter."""

    name = "tradovate"
    # This REST adapter currently submits independent orders.  It does not implement a
    # native OCO bracket, reduce-only/close-position exits, or authoritative asynchronous
    # cancellation confirmation.  Advertising anything stronger would make a future
    # Stage-2 factory look safer than the route really is.
    capabilities = BrokerCapabilities(
        external_execution=True,
        server_side_oco=False,
        reduce_only_or_close_position=False,
        authoritative_cancel_status=False,
        exact_terminal_order_history=False,
        authoritative_session_execution_history=False,
        account_owner_fencing=False,
    )

    def __init__(
        self,
        instrument: InstrumentSpec,
        *,
        environment: Environment = Environment.DEMO,
        credentials: Credentials | None = None,
        transport: Transport | None = None,
        clock: Clock | None = None,
        symbol: str = "",
        timeout: float = 15.0,
        max_retries: int = 3,
    ) -> None:
        self.instrument = instrument
        self.environment = Environment(environment)
        # Raises LiveTradingDisabled before anything else can happen.
        self.base_url = rest_base_url(self.environment)
        self.clock = clock or SystemClock()
        self.client = RestClient(self.base_url, transport, timeout=timeout,
                                 max_retries=max_retries)
        self.credentials = credentials or load_credentials(self.environment)
        self.auth = Authenticator(self.client, self.credentials, clock=self.clock)
        # Tradovate wants a contract name, normally a concrete expiry such as MNQZ6.
        # Connection resolves it through contract -> maturity -> product and refuses it
        # unless that official product identity matches the configured InstrumentSpec.
        self.symbol = symbol or instrument.symbol
        self._connected = False
        self._events: list[BrokerEvent] = []
        self._account_id: int | None = None
        self._contract_id: int | None = None
        self._contract_names: dict[int, str] = {}
        self._seen_fills: set[str] = set()
        self._order_ids: dict[str, str] = {}  # broker orderId -> our order_id
        self._order_quantities: dict[str, int] = {}
        self._filled_quantities: dict[str, int] = {}

    @property
    def is_paper(self) -> bool:
        return self.environment is Environment.DEMO

    @property
    def execution_route(self) -> str:
        return f"tradovate-{self.environment.value}-rest-api"

    # ------------------------------------------------------------------ connection

    def connect(self) -> None:
        self.auth.token()  # authenticates, raising BrokerAuthError without credentials
        self._account_id = self._resolve_account_id()
        self._contract_id = self._resolve_contract_id()
        self._contract_names[self._contract_id] = self.instrument.symbol
        self._connected = True
        self._emit(EventKind.RECONNECTED, detail=f"tradovate {self.environment.value}")

    def disconnect(self) -> None:
        self._connected = False
        self.auth.invalidate()
        self._emit(EventKind.DISCONNECTED, detail="disconnected")

    def is_connected(self) -> bool:
        return self._connected

    def _require(self) -> str:
        if not self._connected:
            raise NotConnected("tradovate adapter is not connected; call connect() first")
        return self.auth.token()

    def _resolve_account_id(self) -> int:
        accounts = _items(self.client.get("account/list", token=self.auth.token()))
        if not accounts:
            raise OrderRejected("no Tradovate accounts are visible for these credentials")

        try:
            visible_ids = [_positive_int(row.get("id"), "account.id") for row in accounts]
        except BrokerConnectionError as exc:
            raise OrderRejected(f"Tradovate returned an invalid account list: {exc}") from exc

        if self.credentials.account_id:
            try:
                configured_id = _positive_int(
                    self.credentials.account_id, "configured account_id"
                )
            except BrokerConnectionError as exc:
                raise OrderRejected(str(exc)) from exc
            if visible_ids.count(configured_id) != 1:
                raise OrderRejected(
                    f"configured Tradovate account {configured_id} is not uniquely visible"
                )
            return configured_id

        if len(visible_ids) != 1:
            raise OrderRejected(
                "multiple Tradovate accounts are visible; configure an explicit account_id"
            )
        return visible_ids[0]

    def _resolve_contract_id(self) -> int:
        encoded_symbol = quote(self.symbol, safe="")
        rows = _items(
            self.client.get(
                f"contract/find?name={encoded_symbol}", token=self.auth.token()
            )
        )
        if len(rows) != 1:
            raise OrderRejected(
                f"configured Tradovate contract {self.symbol!r} was not uniquely resolved"
            )
        row = rows[0]
        if row.get("name") != self.symbol:
            raise OrderRejected(
                f"Tradovate resolved {self.symbol!r} as {row.get('name')!r}; refusing"
            )
        try:
            contract_id = _positive_int(row.get("id"), "contract.id")
            maturity_id = _positive_int(
                row.get("contractMaturityId"), "contract.contractMaturityId"
            )
            maturity = self._single_identity_row(
                f"contractMaturity/item?id={maturity_id}",
                expected_id=maturity_id,
                entity="contract maturity",
            )
            product_id = _positive_int(
                maturity.get("productId"), "contractMaturity.productId"
            )
            product = self._single_identity_row(
                f"product/item?id={product_id}",
                expected_id=product_id,
                entity="product",
            )
        except BrokerConnectionError as exc:
            raise OrderRejected(f"Tradovate returned an invalid contract: {exc}") from exc
        if product.get("name") != self.instrument.symbol:
            raise OrderRejected(
                f"Tradovate contract {self.symbol!r} belongs to product "
                f"{product.get('name')!r}, not {self.instrument.symbol!r}"
            )
        return contract_id

    def _single_identity_row(
        self, path: str, *, expected_id: int, entity: str
    ) -> dict:
        rows = _items(self.client.get(path, token=self.auth.token()))
        if len(rows) != 1:
            raise BrokerConnectionError(f"Tradovate {entity} was not uniquely resolved")
        row = rows[0]
        if _positive_int(row.get("id"), f"{entity}.id") != expected_id:
            raise BrokerConnectionError(
                f"Tradovate returned the wrong identity for {entity} {expected_id}"
            )
        return row

    # ------------------------------------------------------------------ orders

    def place_order(self, order: Order) -> OrderAck:
        token = self._require()
        if order.instrument != self.instrument.symbol:
            detail = (
                f"order instrument {order.instrument!r} does not match adapter instrument "
                f"{self.instrument.symbol!r}"
            )
            self._emit(EventKind.REJECTED, order_id=order.order_id, detail=detail)
            raise OrderRejected(detail)
        body = {
            "accountSpec": self.credentials.account_spec or self.credentials.name,
            "accountId": self._account_id,
            "action": _ACTION[order.side],
            "symbol": self.symbol,
            "orderQty": int(order.quantity),
            "orderType": _ORDER_TYPE[order.order_type],
            "timeInForce": _TIME_IN_FORCE[order.time_in_force],
            # Required by exchange policy for anything not triggered by a human.
            "isAutomated": True,
        }
        if order.limit_price is not None:
            body["price"] = self.instrument.round_to_tick(order.limit_price)
        if order.stop_price is not None:
            body["stopPrice"] = self.instrument.round_to_tick(order.stop_price)

        response = self.client.post("order/placeorder", body, token=token)

        failure = response.get("failureReason") or response.get("failureText")
        if failure:
            self._emit(EventKind.REJECTED, order_id=order.order_id, detail=str(failure))
            raise OrderRejected(f"tradovate rejected {order.order_id}: {failure}")

        broker_order_id = str(response.get("orderId") or response.get("id") or "")
        if not broker_order_id:
            raise OrderRejected(f"no orderId in the placeorder response: {response}")

        self._order_ids[broker_order_id] = order.order_id
        self._order_quantities[broker_order_id] = order.quantity
        self._filled_quantities[broker_order_id] = 0
        self._emit(EventKind.ACCEPTED, order_id=order.order_id,
                   broker_order_id=broker_order_id,
                   detail=f"{body['orderType']} {body['action']} x{body['orderQty']}")
        return OrderAck(
            order_id=order.order_id,
            broker_order_id=broker_order_id,
            status=OrderStatus.SUBMITTED,
            accepted_at=self._now(),
        )

    def cancel_order(self, broker_order_id: str) -> None:
        token = self._require()
        self.client.post("order/cancelorder", {"orderId": _as_int(broker_order_id)},
                         token=token)
        self._emit(EventKind.CANCEL_REQUESTED,
                   order_id=self._order_ids.get(broker_order_id, ""),
                   broker_order_id=broker_order_id, detail="cancel requested")

    # ------------------------------------------------------------------ state

    def get_orders(self) -> list[BrokerOrderState]:
        token = self._require()
        account_id = self._selected_account_id()
        out = []
        rows = _items(
            self.client.get(f"order/deps?masterid={account_id}", token=token)
        )
        for row in rows:
            row_account_id = _positive_int(row.get("accountId"), "order.accountId")
            if row_account_id != account_id:
                continue
            broker_order_id = str(row.get("id", ""))
            out.append(
                BrokerOrderState(
                    broker_order_id=broker_order_id,
                    order_id=self._order_ids.get(broker_order_id, ""),
                    status=_STATUS.get(row.get("ordStatus", ""), OrderStatus.SUBMITTED),
                    filled_quantity=int(row.get("cumQty") or 0),
                    average_fill_price=float(row.get("avgPx") or 0.0),
                    detail=str(row.get("ordStatus", "")),
                )
            )
        return out

    def get_positions(self) -> list[BrokerPosition]:
        token = self._require()
        account_id = self._selected_account_id()
        out = []
        rows = _items(
            self.client.get(f"position/deps?masterid={account_id}", token=token)
        )
        for row in rows:
            row_account_id = _positive_int(row.get("accountId"), "position.accountId")
            if row_account_id != account_id:
                continue
            quantity = _signed_int(row.get("netPos"), "position.netPos")
            if quantity == 0:
                continue
            contract_id = _positive_int(row.get("contractId"), "position.contractId")
            out.append(
                BrokerPosition(
                    instrument=self._instrument_name(contract_id, token=token),
                    quantity=quantity,
                    average_price=float(row.get("netPrice") or 0.0),
                )
            )
        return out

    def get_account(self) -> BrokerAccount:
        token = self._require()
        account_id = self._selected_account_id()
        accounts = _items(self.client.get("account/list", token=token))
        matches = [
            row
            for row in accounts
            if _positive_int(row.get("id"), "account.id") == account_id
        ]
        if len(matches) != 1:
            raise BrokerConnectionError(
                f"selected Tradovate account {account_id} is not uniquely visible"
            )
        row = matches[0]
        cash = float(row.get("cashBalance") or row.get("totalCashValue") or 0.0)
        return BrokerAccount(
            account_id=str(account_id),
            equity=float(row.get("totalCashValue") or cash),
            cash=cash,
            realized_pnl=float(row.get("realizedPnL") or 0.0),
            unrealized_pnl=float(row.get("openPnL") or 0.0),
            is_paper=self.is_paper,
            extra={"name": row.get("name", "")},
        )

    def poll_events(self) -> list[BrokerEvent]:
        """Drain queued events, after folding in any fills seen since the last call.

        v1 polls `/fill/list` rather than consuming the user WebSocket. Polling is slower
        but has no reconnect semantics to get wrong, and this adapter is not the default —
        see docs/LIMITATIONS.md.
        """
        if self._connected:
            self._collect_fills()
        events, self._events = self._events, []
        return events

    def _collect_fills(self) -> None:
        try:
            rows = _items(self.client.get("fill/list", token=self.auth.token()))
        except Exception as exc:  # a polling failure must not take the runner down
            self._emit(EventKind.DISCONNECTED, detail=f"fill poll failed: {exc}")
            return

        for row in rows:
            fill_id = str(row.get("id", ""))
            if not fill_id or fill_id in self._seen_fills:
                continue

            broker_order_id = str(row.get("orderId", ""))
            order_id = self._order_ids.get(broker_order_id)
            if order_id is None:
                # fill/list is not account scoped.  Only fills joined to an order this
                # adapter submitted can safely be projected into this broker instance.
                self._seen_fills.add(fill_id)
                continue

            try:
                contract_id = _positive_int(row.get("contractId"), "fill.contractId")
                if contract_id != self._selected_contract_id():
                    raise BrokerConnectionError(
                        f"fill {fill_id} contract {contract_id} does not match configured "
                        f"contract {self._selected_contract_id()}"
                    )
                quantity = _positive_int(row.get("qty"), "fill.qty")
                expected_quantity = self._order_quantities[broker_order_id]
                cumulative_quantity = (
                    self._filled_quantities.get(broker_order_id, 0) + quantity
                )
                if cumulative_quantity > expected_quantity:
                    raise BrokerConnectionError(
                        f"fill {fill_id} would overfill order {broker_order_id}: "
                        f"{cumulative_quantity} > {expected_quantity}"
                    )
                side = _fill_side(row.get("action"))
                price = _positive_finite_float(row.get("price"), "fill.price")
                commission = _finite_float(
                    row.get("commission") or 0.0, "fill.commission"
                )
                is_partial = cumulative_quantity < expected_quantity
                fill = Fill(
                    fill_id=new_id("fil"),
                    order_id=order_id,
                    timestamp=_parse_time(row.get("timestamp"), self._now()),
                    instrument=self.instrument.symbol,
                    side=side,
                    quantity=quantity,
                    price=price,
                    commission_usd=commission,
                    broker_fill_id=fill_id,
                    is_partial=is_partial,
                )
            except (BrokerConnectionError, KeyError, TypeError, ValueError) as exc:
                self._seen_fills.add(fill_id)
                self._emit(
                    EventKind.DISCONNECTED,
                    order_id=order_id,
                    broker_order_id=broker_order_id,
                    detail=f"fill projection failed: {exc}",
                )
                continue

            self._seen_fills.add(fill_id)
            self._filled_quantities[broker_order_id] = cumulative_quantity
            self._emit(EventKind.PARTIAL_FILL if is_partial else EventKind.FILL,
                       order_id=order_id,
                       broker_order_id=broker_order_id, fill=fill,
                       detail=(
                           f"{quantity} @ {fill.price}; cumulative "
                           f"{cumulative_quantity}/{expected_quantity}"
                       ))

    # ------------------------------------------------------------------ helpers

    def _emit(self, kind: EventKind, **kwargs) -> BrokerEvent:
        event = BrokerEvent(kind=kind, timestamp=self._now(), **kwargs)
        self._events.append(event)
        return event

    def _now(self) -> datetime:
        return self.clock.now().astimezone(MARKET_TZ)

    def _selected_account_id(self) -> int:
        if self._account_id is None:
            raise NotConnected("Tradovate account identity is not resolved")
        return self._account_id

    def _selected_contract_id(self) -> int:
        if self._contract_id is None:
            raise NotConnected("Tradovate contract identity is not resolved")
        return self._contract_id

    def _instrument_name(self, contract_id: int, *, token: str) -> str:
        cached = self._contract_names.get(contract_id)
        if cached is not None:
            return cached

        rows = _items(
            self.client.get(f"contract/item?id={contract_id}", token=token)
        )
        if len(rows) != 1:
            raise BrokerConnectionError(
                f"Tradovate contract {contract_id} was not uniquely resolved"
            )
        row = rows[0]
        resolved_id = _positive_int(row.get("id"), "contract.id")
        name = row.get("name")
        if resolved_id != contract_id or not isinstance(name, str) or not name.strip():
            raise BrokerConnectionError(
                f"Tradovate returned an invalid identity for contract {contract_id}"
            )
        self._contract_names[contract_id] = name
        return name


def _items(body: dict) -> list[dict]:
    """Tradovate list endpoints return a bare JSON array; the transport wraps it."""
    if isinstance(body, list):
        return body
    items = body.get("items")
    if isinstance(items, list):
        return items
    return [body] if body and "id" in body else []


def _as_int(value: str) -> int | str:
    try:
        return int(value)
    except (TypeError, ValueError):
        return value


def _positive_int(value, field: str) -> int:
    parsed = _strict_int(value, field)
    if parsed <= 0:
        raise BrokerConnectionError(f"{field} must be a positive integer")
    return parsed


def _signed_int(value, field: str) -> int:
    return _strict_int(value, field)


def _strict_int(value, field: str) -> int:
    if isinstance(value, bool):
        raise BrokerConnectionError(f"{field} must be an integer")
    if isinstance(value, int):
        return value
    if isinstance(value, str):
        raw = value.strip()
        if raw and (raw.isdecimal() or (raw.startswith("-") and raw[1:].isdecimal())):
            return int(raw)
    raise BrokerConnectionError(f"{field} must be an integer")


def _fill_side(value) -> Side:
    if value == "Buy":
        return Side.BUY
    if value == "Sell":
        return Side.SELL
    raise BrokerConnectionError(f"fill.action must be 'Buy' or 'Sell', got {value!r}")


def _positive_finite_float(value, field: str) -> float:
    parsed = _finite_float(value, field)
    if parsed <= 0:
        raise BrokerConnectionError(f"{field} must be positive")
    return parsed


def _finite_float(value, field: str) -> float:
    if isinstance(value, bool):
        raise BrokerConnectionError(f"{field} must be numeric")
    try:
        parsed = float(value)
    except (TypeError, ValueError) as exc:
        raise BrokerConnectionError(f"{field} must be numeric") from exc
    if not isfinite(parsed):
        raise BrokerConnectionError(f"{field} must be finite")
    return parsed


def _parse_time(raw, fallback: datetime) -> datetime:
    if not raw:
        return fallback
    try:
        parsed = datetime.fromisoformat(str(raw).replace("Z", "+00:00"))
    except ValueError:
        return fallback
    if parsed.tzinfo is None:
        from datetime import UTC

        parsed = parsed.replace(tzinfo=UTC)
    return parsed.astimezone(MARKET_TZ)
