"""Tradovate demo broker adapter.

Implements `BrokerAdapter` against the documented REST endpoints:

| purpose | call |
|---|---|
| authenticate | `POST /auth/accesstokenrequest` (see `auth.py`) |
| place an order | `POST /order/placeorder` |
| cancel an order | `POST /order/cancelorder` |
| working orders | `GET /order/list` |
| positions | `GET /position/list` |
| accounts | `GET /account/list` |

**`isAutomated` is always true.** Exchange policy requires any order not physically
triggered by a human to be flagged as automated. Every order this system sends is
generated by code, so the flag is set unconditionally rather than being configurable —
there is no correct value of `false` for this application, and a configurable one is a
misreporting waiting to happen.

**This adapter reaches a demo host only.** `auth.rest_base_url` raises
`LiveTradingDisabled` for the live environment, so there is no path from here to a
real-money venue in v1.
"""

from __future__ import annotations

from datetime import datetime

from ...core.clock import MARKET_TZ, Clock, SystemClock
from ...core.models import Fill, Order, new_id
from ...core.types import OrderStatus, OrderType, Side
from ...instruments.registry import InstrumentSpec
from ..base import (
    BrokerAccount,
    BrokerCapabilities,
    BrokerEvent,
    BrokerOrderState,
    BrokerPosition,
    EventKind,
    NotConnected,
    OrderAck,
    OrderRejected,
)
from .auth import Authenticator, Credentials, Environment, load_credentials, rest_base_url
from .transport import RestClient, Transport

# Tradovate's vocabulary, mapped once.
_ACTION = {Side.BUY: "Buy", Side.SELL: "Sell"}
_ORDER_TYPE = {
    OrderType.MARKET: "Market",
    OrderType.LIMIT: "Limit",
    OrderType.STOP: "Stop",
    OrderType.STOP_LIMIT: "StopLimit",
}
_STATUS = {
    "Working": OrderStatus.ACCEPTED,
    "Completed": OrderStatus.FILLED,
    "Filled": OrderStatus.FILLED,
    "Canceled": OrderStatus.CANCELLED,
    "Cancelled": OrderStatus.CANCELLED,
    "Rejected": OrderStatus.REJECTED,
    "Expired": OrderStatus.EXPIRED,
    "PendingNew": OrderStatus.SUBMITTED,
    "PendingCancel": OrderStatus.CANCEL_REQUESTED,
    "Suspended": OrderStatus.ACCEPTED,
}


class TradovateBroker:
    """Demo-environment Tradovate adapter."""

    name = "tradovate"
    # This REST adapter currently submits independent orders.  It does not implement a
    # native OCO bracket, reduce-only/close-position exits, or authoritative asynchronous
    # cancellation confirmation.  Advertising anything stronger would make a future
    # Stage-2 factory look safer than the route really is.
    capabilities = BrokerCapabilities(
        external_execution=True,
        server_side_oco=False,
        reduce_only_or_close_position=False,
        authoritative_cancel_status=False,
    )

    def __init__(
        self,
        instrument: InstrumentSpec,
        *,
        environment: Environment = Environment.DEMO,
        credentials: Credentials | None = None,
        transport: Transport | None = None,
        clock: Clock | None = None,
        symbol: str = "",
        timeout: float = 15.0,
        max_retries: int = 3,
    ) -> None:
        self.instrument = instrument
        self.environment = Environment(environment)
        # Raises LiveTradingDisabled before anything else can happen.
        self.base_url = rest_base_url(self.environment)
        self.clock = clock or SystemClock()
        self.client = RestClient(self.base_url, transport, timeout=timeout,
                                 max_retries=max_retries)
        self.credentials = credentials or load_credentials(self.environment)
        self.auth = Authenticator(self.client, self.credentials, clock=self.clock)
        # Tradovate wants a concrete contract, e.g. MNQZ6. Falls back to the root, which
        # some deployments accept and which keeps the simulator and this adapter aligned.
        self.symbol = symbol or instrument.symbol
        self._connected = False
        self._events: list[BrokerEvent] = []
        self._account_id: int | None = None
        self._seen_fills: set[str] = set()
        self._order_ids: dict[str, str] = {}  # broker orderId -> our order_id

    @property
    def is_paper(self) -> bool:
        return self.environment is Environment.DEMO

    # ------------------------------------------------------------------ connection

    def connect(self) -> None:
        self.auth.token()  # authenticates, raising BrokerAuthError without credentials
        self._account_id = self._resolve_account_id()
        self._connected = True
        self._emit(EventKind.RECONNECTED, detail=f"tradovate {self.environment.value}")

    def disconnect(self) -> None:
        self._connected = False
        self.auth.invalidate()
        self._emit(EventKind.DISCONNECTED, detail="disconnected")

    def is_connected(self) -> bool:
        return self._connected

    def _require(self) -> str:
        if not self._connected:
            raise NotConnected("tradovate adapter is not connected; call connect() first")
        return self.auth.token()

    def _resolve_account_id(self) -> int:
        if self.credentials.account_id:
            return int(self.credentials.account_id)
        accounts = _items(self.client.get("account/list", token=self.auth.token()))
        if not accounts:
            raise OrderRejected("no Tradovate accounts are visible for these credentials")
        return int(accounts[0]["id"])

    # ------------------------------------------------------------------ orders

    def place_order(self, order: Order) -> OrderAck:
        token = self._require()
        body = {
            "accountSpec": self.credentials.account_spec or self.credentials.name,
            "accountId": self._account_id,
            "action": _ACTION[order.side],
            "symbol": self.symbol,
            "orderQty": int(order.quantity),
            "orderType": _ORDER_TYPE[order.order_type],
            # Required by exchange policy for anything not triggered by a human.
            "isAutomated": True,
        }
        if order.limit_price is not None:
            body["price"] = self.instrument.round_to_tick(order.limit_price)
        if order.stop_price is not None:
            body["stopPrice"] = self.instrument.round_to_tick(order.stop_price)

        response = self.client.post("order/placeorder", body, token=token)

        failure = response.get("failureReason") or response.get("failureText")
        if failure:
            self._emit(EventKind.REJECTED, order_id=order.order_id, detail=str(failure))
            raise OrderRejected(f"tradovate rejected {order.order_id}: {failure}")

        broker_order_id = str(response.get("orderId") or response.get("id") or "")
        if not broker_order_id:
            raise OrderRejected(f"no orderId in the placeorder response: {response}")

        self._order_ids[broker_order_id] = order.order_id
        self._emit(EventKind.ACCEPTED, order_id=order.order_id,
                   broker_order_id=broker_order_id,
                   detail=f"{body['orderType']} {body['action']} x{body['orderQty']}")
        return OrderAck(
            order_id=order.order_id,
            broker_order_id=broker_order_id,
            status=OrderStatus.SUBMITTED,
            accepted_at=self._now(),
        )

    def cancel_order(self, broker_order_id: str) -> None:
        token = self._require()
        self.client.post("order/cancelorder", {"orderId": _as_int(broker_order_id)},
                         token=token)
        self._emit(EventKind.CANCEL_REQUESTED,
                   order_id=self._order_ids.get(broker_order_id, ""),
                   broker_order_id=broker_order_id, detail="cancel requested")

    # ------------------------------------------------------------------ state

    def get_orders(self) -> list[BrokerOrderState]:
        token = self._require()
        out = []
        for row in _items(self.client.get("order/list", token=token)):
            broker_order_id = str(row.get("id", ""))
            out.append(
                BrokerOrderState(
                    broker_order_id=broker_order_id,
                    order_id=self._order_ids.get(broker_order_id, ""),
                    status=_STATUS.get(row.get("ordStatus", ""), OrderStatus.SUBMITTED),
                    filled_quantity=int(row.get("cumQty") or 0),
                    average_fill_price=float(row.get("avgPx") or 0.0),
                    detail=str(row.get("ordStatus", "")),
                )
            )
        return out

    def get_positions(self) -> list[BrokerPosition]:
        token = self._require()
        out = []
        for row in _items(self.client.get("position/list", token=token)):
            quantity = int(row.get("netPos") or 0)
            if quantity == 0:
                continue
            out.append(
                BrokerPosition(
                    instrument=self.instrument.symbol,
                    quantity=quantity,
                    average_price=float(row.get("netPrice") or 0.0),
                )
            )
        return out

    def get_account(self) -> BrokerAccount:
        token = self._require()
        accounts = _items(self.client.get("account/list", token=token))
        row = next(
            (a for a in accounts if int(a.get("id", -1)) == self._account_id),
            accounts[0] if accounts else {},
        )
        cash = float(row.get("cashBalance") or row.get("totalCashValue") or 0.0)
        return BrokerAccount(
            account_id=str(row.get("id", self._account_id or "")),
            equity=float(row.get("totalCashValue") or cash),
            cash=cash,
            realized_pnl=float(row.get("realizedPnL") or 0.0),
            unrealized_pnl=float(row.get("openPnL") or 0.0),
            is_paper=self.is_paper,
            extra={"name": row.get("name", "")},
        )

    def poll_events(self) -> list[BrokerEvent]:
        """Drain queued events, after folding in any fills seen since the last call.

        v1 polls `/fill/list` rather than consuming the user WebSocket. Polling is slower
        but has no reconnect semantics to get wrong, and this adapter is not the default —
        see docs/LIMITATIONS.md.
        """
        if self._connected:
            self._collect_fills()
        events, self._events = self._events, []
        return events

    def _collect_fills(self) -> None:
        try:
            rows = _items(self.client.get("fill/list", token=self.auth.token()))
        except Exception as exc:  # a polling failure must not take the runner down
            self._emit(EventKind.DISCONNECTED, detail=f"fill poll failed: {exc}")
            return

        for row in rows:
            fill_id = str(row.get("id", ""))
            if not fill_id or fill_id in self._seen_fills:
                continue
            self._seen_fills.add(fill_id)

            broker_order_id = str(row.get("orderId", ""))
            order_id = self._order_ids.get(broker_order_id, "")
            quantity = int(row.get("qty") or 0)
            if quantity <= 0:
                continue
            side = Side.BUY if str(row.get("action", "Buy")) == "Buy" else Side.SELL
            fill = Fill(
                fill_id=new_id("fil"),
                order_id=order_id,
                timestamp=_parse_time(row.get("timestamp"), self._now()),
                instrument=self.instrument.symbol,
                side=side,
                quantity=quantity,
                price=float(row.get("price") or 0.0),
                commission_usd=float(row.get("commission") or 0.0),
                broker_fill_id=fill_id,
                is_partial=bool(row.get("active", False)),
            )
            self._emit(EventKind.FILL, order_id=order_id,
                       broker_order_id=broker_order_id, fill=fill,
                       detail=f"{quantity} @ {fill.price}")

    # ------------------------------------------------------------------ helpers

    def _emit(self, kind: EventKind, **kwargs) -> BrokerEvent:
        event = BrokerEvent(kind=kind, timestamp=self._now(), **kwargs)
        self._events.append(event)
        return event

    def _now(self) -> datetime:
        return self.clock.now().astimezone(MARKET_TZ)


def _items(body: dict) -> list[dict]:
    """Tradovate list endpoints return a bare JSON array; the transport wraps it."""
    if isinstance(body, list):
        return body
    items = body.get("items")
    if isinstance(items, list):
        return items
    return [body] if body and "id" in body else []


def _as_int(value: str) -> int | str:
    try:
        return int(value)
    except (TypeError, ValueError):
        return value


def _parse_time(raw, fallback: datetime) -> datetime:
    if not raw:
        return fallback
    try:
        parsed = datetime.fromisoformat(str(raw).replace("Z", "+00:00"))
    except ValueError:
        return fallback
    if parsed.tzinfo is None:
        from datetime import UTC

        parsed = parsed.replace(tzinfo=UTC)
    return parsed.astimezone(MARKET_TZ)
